name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
          ~/.cache/pip
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Poetry via Action
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '2.1.1'

    - name: Install dependencies
      run: |
        poetry install

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        poetry run pytest --junitxml=test-results/result.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test-results/**/*.xml
          test-results/**/*.trx
          test-results/**/*.json
